-- MySQL Script generated by MySQL Workbench
-- Sat 04 Jul 2026 03:11:04 BST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wdadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wdadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wdadb` ;
USE `wdadb` ;

-- -----------------------------------------------------
-- Table `wdadb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdadb`.`user` ;

CREATE TABLE IF NOT EXISTS `wdadb`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wdadb`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdadb`.`location` ;

CREATE TABLE IF NOT EXISTS `wdadb`.`location` (
  `location_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `capacity` INT NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wdadb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdadb`.`category` ;

CREATE TABLE IF NOT EXISTS `wdadb`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wdadb`.`organiser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdadb`.`organiser` ;

CREATE TABLE IF NOT EXISTS `wdadb`.`organiser` (
  `organiser_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`organiser_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_org_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `wdadb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wdadb`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdadb`.`event` ;

CREATE TABLE IF NOT EXISTS `wdadb`.`event` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `location_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `organiser_id` INT NULL,
  `event_name` VARCHAR(45) NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `conditions` VARCHAR(45) NULL,
  `booking_deadline` DATETIME NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `original_price` DECIMAL(10,2) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`event_id`),
  INDEX `location_id_idx` (`location_id` ASC) VISIBLE,
  INDEX `category_id_idx` (`category_id` ASC) VISIBLE,
  INDEX `organiser_id_idx` (`organiser_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_venue`
    FOREIGN KEY (`location_id`)
    REFERENCES `wdadb`.`location` (`location_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `wdadb`.`category` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_organiser`
    FOREIGN KEY (`organiser_id`)
    REFERENCES `wdadb`.`organiser` (`organiser_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wdadb`.`booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdadb`.`booking` ;

CREATE TABLE IF NOT EXISTS `wdadb`.`booking` (
  `booking_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  `booked_on` DATETIME NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `booked_base_price` DECIMAL(10,2) NOT NULL,
  `days_booked` INT NOT NULL,
  `attendee_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`booking_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `event_id_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `fk_booked_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `wdadb`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booked_event`
    FOREIGN KEY (`event_id`)
    REFERENCES `wdadb`.`event` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wdadb`.`suitability`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdadb`.`suitability` ;

CREATE TABLE IF NOT EXISTS `wdadb`.`suitability` (
  `suitability_id` INT NOT NULL AUTO_INCREMENT,
  `location_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`suitability_id`),
  INDEX `location_id_idx` (`location_id` ASC) VISIBLE,
  INDEX `category_id_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `location_id_suit`
    FOREIGN KEY (`location_id`)
    REFERENCES `wdadb`.`location` (`location_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `category_id_suit`
    FOREIGN KEY (`category_id`)
    REFERENCES `wdadb`.`category` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wdadb`.`cancel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdadb`.`cancel` ;

CREATE TABLE IF NOT EXISTS `wdadb`.`cancel` (
  `cancellation_id` INT NOT NULL AUTO_INCREMENT,
  `booking_id` INT NOT NULL,
  `cancellation_fee` DECIMAL(10,2) NOT NULL,
  `cancelled_on` DATETIME NOT NULL,
  PRIMARY KEY (`cancellation_id`),
  UNIQUE INDEX `booking_id_UNIQUE` (`booking_id` ASC) VISIBLE,
  CONSTRAINT `fk_cancel_booking`
    FOREIGN KEY (`booking_id`)
    REFERENCES `wdadb`.`booking` (`booking_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wdadb`.`discount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdadb`.`discount` ;

CREATE TABLE IF NOT EXISTS `wdadb`.`discount` (
  `discount_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `percent` DECIMAL(5,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`discount_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wdadb`.`booking_discounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdadb`.`booking_discounts` ;

CREATE TABLE IF NOT EXISTS `wdadb`.`booking_discounts` (
  `booking_id` INT NOT NULL,
  `discount_id` INT NOT NULL,
  `amount_deducted` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`booking_id`, `discount_id`),
  INDEX `discount_id_idx` (`discount_id` ASC) VISIBLE,
  CONSTRAINT `fk_discount_type`
    FOREIGN KEY (`discount_id`)
    REFERENCES `wdadb`.`discount` (`discount_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_discounted_booking`
    FOREIGN KEY (`booking_id`)
    REFERENCES `wdadb`.`booking` (`booking_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
